Adding alertmanager as job by default
Tina-pm/ansible-roles pull request #1
Opened 2024-06-11 16:54 UTC by mrfussion

2024-06-12 10:08 UTC, sim6 requested changes

2024-06-12 10:08 UTC, sim6 commented on prometheus/vars/main.yaml
> +  - targets: '{{ (prometheus__alertmanagers or [] | list }}'
Forgotten parenthesis closure.
```suggestion
  - targets: '{{ (prometheus__alertmanagers or []) | list }}'
```

2024-06-12 17:17 UTC, NightTsarina commented on prometheus/vars/main.yaml
> +__alertmanager_scrape_config:
This is good, but it won't do anything unless you add this variable to `__all_scrape_configs`

2024-06-17 13:31 UTC, NightTsarina approved these changes

2024-06-17 13:54 UTC, merged